// Grimoire — book data

const BOOKS = {
  atlas: {
    title: 'The Atlas of Forgotten Names',
    author: 'Vera Ashcroft',
    authorShort: 'V. ASHCROFT',
    narrator: 'Idris Okafor',
    palette: ['#3D2860', '#0D0B12', '#C9A24A'],
    sigil: 'moon',
    duration: '11h 42m',
    progress: 0.34,
    chapters: 24,
    chapter: 'Chapter 7 — The Cartographer\'s Daughter',
    rating: 4.7,
    year: 2023,
    kind: 'both', // audio + text
    genre: 'Literary Fiction',
  },
  black_garden: {
    title: 'A Black Garden',
    author: 'Magda Lin',
    authorShort: 'M. LIN',
    narrator: 'Saoirse Dunne',
    palette: ['#0F2A1F', '#08070B', '#6FB3A0'],
    sigil: 'tri',
    duration: '8h 15m',
    progress: 0.12,
    rating: 4.4,
    chapter: 'Chapter 3 — Hyssop',
    genre: 'Magical Realism',
  },
  hollow_king: {
    title: 'The Hollow King',
    author: 'T. R. Mercer',
    authorShort: 'T.R. MERCER',
    palette: ['#4A1020', '#0D0B12', '#E8A87C'],
    sigil: 'rune',
    duration: '18h 03m',
    progress: 0.78,
    rating: 4.9,
    chapter: 'Chapter 31 — Salt & Iron',
    genre: 'Fantasy',
  },
  salt_wives: {
    title: 'Salt Wives',
    author: 'Nora Okonkwo',
    authorShort: 'N. OKONKWO',
    palette: ['#1B2F44', '#08070B', '#E8E1D1'],
    sigil: 'eye',
    duration: '9h 28m',
    progress: 0,
    rating: 4.6,
    genre: 'Historical Fiction',
  },
  quiet_machines: {
    title: 'Quiet Machines',
    author: 'Felix Ardent',
    authorShort: 'F. ARDENT',
    palette: ['#2C2F3F', '#08070B', '#8B5CF6'],
    sigil: 'circle',
    duration: '6h 51m',
    rating: 4.3,
    genre: 'Sci-Fi',
  },
  vesper: {
    title: 'Vesper',
    author: 'Clémence Roy',
    authorShort: 'C. ROY',
    palette: ['#3A1D4A', '#0D0B12', '#C9A24A'],
    sigil: 'star',
    duration: '5h 12m',
    rating: 4.5,
    genre: 'Poetry',
  },
  widow_tide: {
    title: 'Widow Tide',
    author: 'Hana Meier',
    authorShort: 'H. MEIER',
    palette: ['#193235', '#08070B', '#A0C4C2'],
    sigil: 'moon',
    duration: '12h 20m',
    rating: 4.2,
    genre: 'Thriller',
  },
  ink_bones: {
    title: 'Of Ink and Bones',
    author: 'P. Sundari',
    authorShort: 'P. SUNDARI',
    palette: ['#3B1B1B', '#08070B', '#C9A24A'],
    sigil: 'sun',
    duration: '14h 02m',
    rating: 4.8,
    genre: 'Fantasy',
  },
};

window.BOOKS = BOOKS;
